name: Main
on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches:
      - dev
      - main
  pull_request:
jobs:
  validate:
    name: Validate
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "home-assistant/actions/hassfest@master"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
