name: Main
on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches:
      - dev
      - main
  pull_request:
jobs:
  validate:
    name: Validate
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "home-assistant/actions/hassfest@master"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
  pytest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - name: Install Python modules
        run: |
          pip install -r requirements.test.txt
      - name: Run unit tests
        run: |
          python -m pytest tests
